obj-$(CONFIG_SND_SOC_SAMSUNG_ABOX) += abox_util.o abox_gic.o abox.o abox_rdma.o abox_wdma.o abox_effect.o abox_vss.o
obj-$(CONFIG_SND_SOC_SAMSUNG_ABOX_DEBUG) += abox_dbg.o abox_log.o abox_dump.o
obj-$(CONFIG_SEC_SND_ADAPTATION) += abox_adaptation.o
